<?php

use Illuminate\Database\Seeder;

class DentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('dientes')->insert([
            ['numero' => '11',
            'nombre' => 'incisivo central',
            'arcada' => 'arcada1'],
            ['numero' => '12',
            'nombre' => 'incisivo lateral',
            'arcada' => 'arcada1'],
            ['numero' => '13',
            'nombre' => 'canino',
            'arcada' => 'arcada1'],
            ['numero' => '14',
            'nombre' => 'primer premolar',
            'arcada' => 'arcada1'],
            ['numero' => '15',
            'nombre' => 'segundo premolar',
            'arcada' => 'arcada1'],
            ['numero' => '16',
            'nombre' => 'primer molar',
            'arcada' => 'arcada1'],
            ['numero' => '17',
            'nombre' => 'segundo molar',
            'arcada' => 'arcada1'],
            ['numero' => '18',
            'nombre' => 'tercer molar',
            'arcada' => 'arcada1'],
            ['numero' => '51',
            'nombre' => 'incisivo central',
            'arcada' => 'arcada1'],
            ['numero' => '52',
            'nombre' => 'incisivo lateral',
            'arcada' => 'arcada1'],
            ['numero' => '53',
            'nombre' => 'canino',
            'arcada' => 'arcada1'],
            ['numero' => '54',
            'nombre' => 'primer premolar',
            'arcada' => 'arcada1'],
            ['numero' => '55',
            'nombre' => 'segundo premolar',
            'arcada' => 'arcada1'],
        ]);
        DB::table('dientes')->insert([
            ['numero' => '21',
            'nombre' => 'incisivo central',
            'arcada' => 'arcada2'],
            ['numero' => '22',
            'nombre' => 'incisivo lateral',
            'arcada' => 'arcada2'],
            ['numero' => '23',
            'nombre' => 'canino',
            'arcada' => 'arcada2'],
            ['numero' => '24',
            'nombre' => 'primer premolar',
            'arcada' => 'arcada2'],
            ['numero' => '25',
            'nombre' => 'segundo premolar',
            'arcada' => 'arcada2'],
            ['numero' => '26',
            'nombre' => 'primer molar',
            'arcada' => 'arcada2'],
            ['numero' => '27',
            'nombre' => 'segundo molar',
            'arcada' => 'arcada2'],
            ['numero' => '28',
            'nombre' => 'tercer molar',
            'arcada' => 'arcada2'],
            ['numero' => '61',
            'nombre' => 'incisivo central',
            'arcada' => 'arcada2'],
            ['numero' => '62',
            'nombre' => 'incisivo lateral',
            'arcada' => 'arcada2'],
            ['numero' => '63',
            'nombre' => 'canino',
            'arcada' => 'arcada2'],
            ['numero' => '64',
            'nombre' => 'primer premolar',
            'arcada' => 'arcada2'],
            ['numero' => '65',
            'nombre' => 'segundo premolar',
            'arcada' => 'arcada2'],
        ]);
        DB::table('dientes')->insert([
            ['numero' => '31',
            'nombre' => 'incisivo central',
            'arcada' => 'arcada3'],
            ['numero' => '32',
            'nombre' => 'incisivo lateral',
            'arcada' => 'arcada3'],
            ['numero' => '33',
            'nombre' => 'canino',
            'arcada' => 'arcada3'],
            ['numero' => '34',
            'nombre' => 'primer premolar',
            'arcada' => 'arcada3'],
            ['numero' => '35',
            'nombre' => 'segundo premolar',
            'arcada' => 'arcada3'],
            ['numero' => '36',
            'nombre' => 'primer molar',
            'arcada' => 'arcada3'],
            ['numero' => '37',
            'nombre' => 'segundo molar',
            'arcada' => 'arcada3'],
            ['numero' => '38',
            'nombre' => 'tercer molar',
            'arcada' => 'arcada3'],
            ['numero' => '71',
            'nombre' => 'incisivo central',
            'arcada' => 'arcada3'],
            ['numero' => '72',
            'nombre' => 'incisivo lateral',
            'arcada' => 'arcada3'],
            ['numero' => '73',
            'nombre' => 'canino',
            'arcada' => 'arcada3'],
            ['numero' => '74',
            'nombre' => 'primer premolar',
            'arcada' => 'arcada3'],
            ['numero' => '75',
            'nombre' => 'segundo premolar',
            'arcada' => 'arcada3'],
        ]);
        DB::table('dientes')->insert([
            ['numero' => '41',
            'nombre' => 'incisivo central',
            'arcada' => 'arcada4'],
            ['numero' => '42',
            'nombre' => 'incisivo lateral',
            'arcada' => 'arcada4'],
            ['numero' => '43',
            'nombre' => 'canino',
            'arcada' => 'arcada4'],
            ['numero' => '44',
            'nombre' => 'primer premolar',
            'arcada' => 'arcada4'],
            ['numero' => '45',
            'nombre' => 'segundo premolar',
            'arcada' => 'arcada4'],
            ['numero' => '46',
            'nombre' => 'primer molar',
            'arcada' => 'arcada4'],
            ['numero' => '47',
            'nombre' => 'segundo molar',
            'arcada' => 'arcada4'],
            ['numero' => '48',
            'nombre' => 'tercer molar',
            'arcada' => 'arcada4'],
            ['numero' => '81',
            'nombre' => 'incisivo central',
            'arcada' => 'arcada4'],
            ['numero' => '82',
            'nombre' => 'incisivo lateral',
            'arcada' => 'arcada4'],
            ['numero' => '83',
            'nombre' => 'canino',
            'arcada' => 'arcada4'],
            ['numero' => '84',
            'nombre' => 'primer premolar',
            'arcada' => 'arcada4'],
            ['numero' => '85',
            'nombre' => 'segundo premolar',
            'arcada' => 'arcada4'],
        ]);
    }
}
